import sys
import os
import datetime
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QIcon, QFont
from src.utils import get_resource_path


class RecordWindow(QWidget):
    """TRC 포맷으로 CAN 데이터를 기록하고 보여주며 저장하는 창"""
    def __init__(self, parent=None, bitrates=None):
        super().__init__(parent)
        self.setAttribute(Qt.WA_DeleteOnClose) # 창이 닫힐 때(Close) 메모리에서 안전하게 완전 해제
        self.setWindowTitle("Record CAN Data (Log Viewer)")
        self.setWindowIcon(QIcon(get_resource_path(os.path.join("icon", "recorder.png"))))
        self.resize(750, 500)
        
        self.layout = QVBoxLayout(self)
        
        self.text_edit = QPlainTextEdit()
        self.text_edit.setReadOnly(True)
        self.text_edit.setFont(QFont("Consolas", 10))
        self.text_edit.setMaximumBlockCount(50000) # 너무 많은 로그가 쌓여 화면 렌더링이 멈추는 것 방지
        self.layout.addWidget(self.text_edit)
        
        btn_layout = QHBoxLayout()
        self.btn_save = QPushButton("Save")
        self.btn_close = QPushButton("Close")
        btn_layout.addStretch()
        btn_layout.addWidget(self.btn_save)
        btn_layout.addWidget(self.btn_close)
        self.layout.addLayout(btn_layout)
        
        self.btn_save.clicked.connect(self.save_log)
        self.btn_close.clicked.connect(self.on_btn_close_clicked)
        
        self.log_lines = []
        self.msg_count = 0
        self.is_closed_by_btn = False
        self.is_saved = False
        self.start_timestamp = None
        self.last_offset_ms = 0.0
        self.start_datetime = datetime.datetime.now()
        self.bitrates = bitrates or {1: "500 kBit/s"}
        
        # OLE Date (1899-12-30 기준 날짜 계산)
        self.ole_date = (self.start_datetime - datetime.datetime(1899, 12, 30)).total_seconds() / 86400.0
        
        # 성능 최적화를 위한 텍스트 버퍼 타이머
        self.gui_queue = []
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.flush_gui)
        self.timer.start(100) # 100ms 마다 텍스트 한 번에 렌더링
        
        self.write_header()
        
    def write_header(self):
        header = [
            ";$FILEVERSION=2.1",
            f";$STARTTIME={self.ole_date:.13f}",
            ";$COLUMNS=N,O,T,B,I,d,R,L,D",
            ";",
            f";   Start time: {self.start_datetime.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}",
            ";   Generated by Universal CAN Monitor",
            ";-------------------------------------------------------------------------------",
            ";   Bus  Connection   Net Connection     Protocol  Bit rate",
        ]
        for b, br in self.bitrates.items():
            header.append(f";   {b}    Connection{b}  CAN_Monitor        CAN       {br}")
            
        header.extend([
            ";-------------------------------------------------------------------------------",
            ";   Message    Time    Type    ID     Rx/Tx",
            ";   Number     Offset  |  Bus  [hex]  |  Reserved",
            ";   |          [ms]    |  |    |      |  |  Data Length Code",
            ";   |          |       |  |    |      |  |  |    Data [hex] ...",
            ";   |          |       |  |    |      |  |  |    |",
            ";---+--- ------+------ +- +- --+----- +- +- +--- +- -- -- -- -- -- -- --"
        ])
        self.log_lines.extend(header)
        self.text_edit.appendPlainText("\n".join(header))
        
    def add_log_entry(self, ts, can_id, data, is_ext, is_err, is_fd, is_rx, bus_num=1):
        if is_err: return # 에러 프레임은 생략
        if self.start_timestamp is None:
            self.start_timestamp = ts
            
        self.msg_count += 1
        # 멀티 버스/드라이버 타임스탬프 편차로 인한 음수/역전 시간을 방지합니다.
        offset_ms = max(0.0, (ts - self.start_timestamp) * 1000.0)
        if offset_ms < self.last_offset_ms:
            offset_ms = self.last_offset_ms
        self.last_offset_ms = offset_ms
        can_id_hex = f"{can_id:08X}" if is_ext else f"{can_id:04X}"
        dlc = len(data)
        data_hex = " ".join(f"{b:02X}" for b in data)
        
        msg_type = "FD" if is_fd else "DT"
        direction = "Rx" if is_rx else "Tx"
        line = f"{self.msg_count:>8} {offset_ms:>13.3f} {msg_type} {bus_num} {can_id_hex:>9} {direction} - {dlc:>2}    {data_hex}"
        self.log_lines.append(line)
        self.gui_queue.append(line)
        
    def flush_gui(self):
        if self.gui_queue:
            self.text_edit.appendPlainText("\n".join(self.gui_queue))
            self.gui_queue.clear()
            
    def on_btn_close_clicked(self):
        self.is_closed_by_btn = True
        self.close()
            
    def save_log(self):
        # 실행 파일(.exe) 또는 스크립트(.py)의 기본 위치 확인
        if getattr(sys, 'frozen', False):
            base_dir = os.path.dirname(sys.executable)
        else:
            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            
        try:
            log_dir = os.path.join(base_dir, "Log")
            os.makedirs(log_dir, exist_ok=True) # Log 폴더가 없으면 자동 생성
            
            default_filename = f"CAN_Log_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.trc"
            default_filepath = os.path.join(log_dir, default_filename)
            
            file_path, _ = QFileDialog.getSaveFileName(self, "Save TRC File", default_filepath, "TRC Files (*.trc)")
            if file_path:
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write("\n".join(self.log_lines) + "\n")
                self.is_saved = True
                self.close() # 저장 완료 후 창 자동 닫기
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Failed to save file:\n{str(e)}")

    def auto_save_log(self):
        if getattr(sys, 'frozen', False):
            base_dir = os.path.dirname(sys.executable)
        else:
            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            
        try:
            log_dir = os.path.join(base_dir, "Log")
            os.makedirs(log_dir, exist_ok=True)
            
            default_filename = f"CAN_Log_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.trc"
            default_filepath = os.path.join(log_dir, default_filename)
            
            with open(default_filepath, 'w', encoding='utf-8') as f:
                f.write("\n".join(self.log_lines) + "\n")
            self.is_saved = True
        except Exception:
            pass

    def closeEvent(self, event):
        """창이 닫힐 때 타이머가 계속 동작하여 발생하는 RuntimeError 완벽 차단"""
        if not getattr(self, 'is_closed_by_btn', False) and not getattr(self, 'is_saved', False):
            if self.msg_count > 0:
                self.auto_save_log()
                
        self.timer.stop()
        event.accept()
